server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modeldata
    username: root
    password: Akshay@1995
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop 

